DROP TABLE IF EXISTS STORELOCATOR;

CREATE TABLE STORELOCATOR (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  state VARCHAR(10) NOT NULL,
  city VARCHAR(50) NOT NULL
);

INSERT INTO STORELOCATOR
    (state, city) VALUES
        ('CA', 'Burbank'),
        ('CA','Carson'),
        ('AZ','Tempe'),
        ('CA','Costa Mesa'),
        ('CA','Covina'),
        ('CA','East Palo Alto'),
        ('CA','Emeryville'),
        ('CA','San Diego'),
        ('CA','West Sacramento'),
        ('CO','Centennial'),
        ('CT','New Haven'),
        ('FL','Jacksonville'),
        ('FL','Miami'),
        ('FL','Orlando'),
        ('FL','Sunrise'),
        ('FL','Tampa'),
        ('GA','Atlanta'),
        ('IL','Bolingbrook'),
        ('IL','Schaumburg'),
        ('IN','Fishers'),
        ('KS','Merriam'),
        ('MA','Stoughton'),
        ('MD','Baltimore'),
        ('MD','College Park'),
        ('MI','Canton'),
        ('MN','Bloomington'),
        ('MO','St. Louis'),
        ('NC','Charlotte'),
        ('NJ','Elizabeth'),
        ('NJ','Paramus'),
        ('NV','Las Vegas'),
        ('NY','Brooklyn'),
        ('NY','Long Island'),
        ('NY','Upper East Side'),
        ('OH','Columbus'),
        ('OH','West Chester'),
        ('OR','Portland'),
        ('PA','Conshohocken'),
        ('PA','Pittsburgh'),
        ('PA','South Philadelp'),
        ('TN','Memphis'),
        ('TX','Frisco'),
        ('TX','Grand Prairie'),
        ('TX','Houston'),
        ('TX','Live Oak'),
        ('TX','Round Rock'),
        ('UT','Draper'),
        ('VA','Norfolk'),
        ('VA','Woodbridge'),
        ('WA','Renton'),
        ('WI','Oak Creek')
        ;
